### ISSUE TITLE
ペパランチョンの応募〜設定までを簡潔にしたい　vol.2

### ISSUE THREAD

**Issue by loversnet** [loversnet/slack-bot#2]
## 目的
- これまでのペパランチョンの設定をより簡潔に、そして参加者もエンジニアも有意義になるようにしたい

## これまで
- ペパランチョンで話したい人を指名すると、そのエンジニアとランチができる
 - 話したいエンジニアが決まっていればスムーズ、決まってない場合がその方のバックグラウンドが分からず手配に時間がかかる

## これから
- 決まっている人はこれまで通り教えてもらう
- 決まっていない人はどんな話を聞きたいか、興味あることを聞いて、連絡をもらったタイミングでアレンジできるようにする
- 環境や要望に合う人をアサインすることでペパランチョンが有意義になるし、また転職をより意識してくれるかもしれない

## 具体的に行うこと
- これまでの応募フォームからgoogleフォームを用いて対応する
- フォーム送信をトリガーとして、Slackの#recruitに飛ぶようにする
- 該当メンバーで誰がランチョン適任かを検討し、調整する

**Comment by loversnet** [comment]
https://github.com/3loversnet7/slack-bot/issues/1

こちらで躓いたので、juneさんにご相談。
なんかあっという間に解決してくれたので、私の悩んだ数時間が嘘のようだった。

## 変えたこと
【前】googleフォームで送信後、Slackに通知するようにする
【後】googleフォームで送信後、その内容をissueに立てるようにする
　　　＋issueが立ったらSlackに通知するようにする

まずはissueに立てるところから。
その後、Slack通知の仕組みを勉強する。

### テスト用のリポジトリを立てる
- GHEで立てた　⇒　https://git.pepabo.com/3loversnet7/test

### APIトークンの発行
[Personal access tokens](https://git.pepabo.com/settings/tokens)　⇒　New personal access token　でToken descriptionの入力をrepoをチェックして Generate tokenすると、APIが発行される
※絶対に他人に共有しない！

### コピーをすることからはじめる
- 以前hsbtさんが書いていたものを引用させてもらう
　https://git.pepabo.com/hsbt/gform-submission

### エディタにのせる
- まずは最小限の情報から
```
function onFormSubmit(e) {

  var ghToken = "【issueのトークン】";

  var itemResponses = e.response.getItemResponses();
  var name = itemResponses[1].getResponse();
  var location = itemResponses[3].getResponse();

  var title = name　+ " : " + location;

  var body =
      "### " + title + "\n" +
      title + "\n" +
      title;

  var payload = {
    "title": title,
    "body": body
  };

  var options = {
    "method": "POST",
    "contentType": "application/json",
    "payload": JSON.stringify(payload)
  };

  var response = UrlFetchApp.fetch("https://git.pepabo.com/api/v3/repos/3loversnet7/test/issues?access_token=" + ghToken, options);
```

- コード内の[1][3]という数字は、アンケートフォーム（回答のスプレッドシート）の列に該当する
  - ただし、読み込みによっては数字がずれる可能性があるので、テストしながら様子を見る

**Comment by loversnet** [comment]
### カスタマイズしてみる
```
function onFormSubmit(e) {

  var ghToken = "【APIトークン】";

  var itemResponses = e.response.getItemResponses();
  var name = itemResponses[1].getResponse();
  var location = itemResponses[3].getResponse();
  var date = itemResponses[4].getResponse();
  var talk = itemResponses[5].getResponse();
  var person = itemResponses[6].getResponse();
  var output = itemResponses[7].getResponse();
  var other = itemResponses[8].getResponse();
  

  var title = name　+ " : " + location+ " : " + date;

  var body =
      "### " + " 名前 : "　+ name + "\n" +
      "### " + " 希望場所 : "　+ location + "\n" +
      "### " + " 希望日 : "　+ date + "\n" +
      "#### " +" 聞きたいこと : "　+　talk + "\n" +
      "#### " +" 話したい人　: "　+　person + "\n" +
      "#### " +" アウトプット　: "　+　output + "\n" +
      "#### " +" その他　: "　+　other + "\n";

  var payload = {
    "title": title,
    "body": body
  };

  var options = {
    "method": "POST",
    "contentType": "application/json",
    "payload": JSON.stringify(payload)
  };

  var response = UrlFetchApp.fetch("https://git.pepabo.com/api/v3/repos/3loversnet7/test/issues?access_token=" + ghToken, options);
```

**Comment by loversnet** [comment]
こちら一旦できたのでクローズ！
やったー

**Comment by 3loversnet7** [comment]
function onFormSubmit(e) {

  var ghToken = "【APIトークン】";

  var itemResponses = e.response.getItemResponses();
  var name = itemResponses[1].getResponse();
  var location = itemResponses[3].getResponse();
  var date = itemResponses[4].getResponse();
  var talk = itemResponses[5].getResponse();
  var person = itemResponses[6].getResponse();
  var output = itemResponses[7].getResponse();
  var other = itemResponses[8].getResponse();
  

  var title = name　+ " : " + location+ " : " + date;

  var body =
      "### " + " 名前 : "　+ name + "\n" +
      "### " + " 希望場所 : "　+ location + "\n" +
      "### " + " 希望日 : "　+ date + "\n" +
      "#### " +" 聞きたいこと : "　+　talk + "\n" +
      "#### " +" 話したい人　: "　+　person + "\n" +
      "#### " +" アウトプット　: "　+　output + "\n" +
      "#### " +" その他　: "　+　other + "\n";

  var payload = {
    "title": title,
    "body": body
  };

  var options = {
    "method": "POST",
    "contentType": "application/json",
    "payload": JSON.stringify(payload)
  };

  var response = UrlFetchApp.fetch("https://git.pepabo.com/api/v3/repos/recruiting/pepaluncheon-secret/issues?access_token=" + ghToken, options);

**Comment by loversnet** [comment]
3loversnet7/test
ここを飛ばしたいリポジトリに変更すると、そのリポジトリにissueが立つようになる
